## cookie:PROP_TEST_KEY=1771155677468.16883c865e857a97b539b90d3a564bbe438f442f6c0e14ac7e03b16cbeae90ce;
## cookie:PROP_TEST_KEY=1770977799430.551d3eddd43512a1afd41356bfaa7f4d98edd6f02a57905dd1708c1cc9357d56;
## cookie:PROP_TEST_KEY=1771335057714.df4aacbeea52e30aac6cc6e8af4277d7dfac9f8bffb04b80986e20ad3bfb5ee1;

### 시/도 조회
GET https://new.land.naver.com/api/regions/list?cortarNo=0000000000
accept:*/*
accept-encoding:identity
accept-language:ko;q=0.7
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlJFQUxFU1RBVEUiLCJpYXQiOjE3NzA5Nzc3OTksImV4cCI6MTc3MDk4ODU5OX0.KtZaFoCPtVy0DfFhF8KMbpJ-IUgE_CDNhO4HQtfzGt0
cache-control:no-cache
cookie:PROP_TEST_KEY=1771155677468.16883c865e857a97b539b90d3a564bbe438f442f6c0e14ac7e03b16cbeae90ce;
pragma:no-cache
priority:u=1, i
sec-ch-ua:"Not:A-Brand";v="99", "Brave";v="145", "Chromium";v="145"
sec-ch-ua-mobile:?0
sec-ch-ua-platform:"Windows"
sec-fetch-dest:empty
sec-fetch-mode:cors
sec-fetch-site:same-origin
sec-gpc:1
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36


## 결과
{
  "regionList": [
    {
      "cortarNo": "1100000000",
      "centerLat": 37.566427,
      "centerLon": 126.977872,
      "cortarName": "서울시",
      "cortarType": "city"
    },
    {
      "cortarNo": "4100000000",
      "centerLat": 37.274939,
      "centerLon": 127.008689,
      "cortarName": "경기도",
      "cortarType": "city"
    }
  ]
}
